### ISSUE TITLE
登录错误的提示过于模糊

### ISSUE THREAD

**Issue by Mrkk1** [Fatpandac/hackcqooc#13]
建议将core下的 __login_by_pwd 错误return 由
return Msg().processing("登录失败，可能需要官网登录后重试", 400, data)
更改为
return  Msg().processing(data['msg'], 400, data)
直接返回官网错误信息 不在做模糊封装

**Comment by Fatpandac** [comment]
很高兴能收到你的 issue。
那地方确实应该如此，如果可以的话，我希望你来修改并提交相应的 PR。🤗

**Comment by Mrkk1** [comment]
好的 我已经提交到pr
