### ISSUE TITLE
大佬，一直登录失败

### ISSUE THREAD

**Issue by abai2020** [Fatpandac/hackcqooc#6]
[31m
Step 1, init object[0m
[32mcore = Core(None, None)[0m
[31m
Step 2, login to the cqooc, get cookies[0m
[32mcore.login()[0m
{
  "code": 400,
  "msg": "登录失败，可能需要官网登录后重试",
  "status": "fail",
  "data": null
}
[31m
Step 3, get the course list[0m
[32mcore.get_course()[0m
{
  "meta": {
    "total": "0",
    "start": "1",
    "size": "0"
  },
  "data": [],
  "code": 200,
  "status": "ok",
  "msg": "获取课程成功"
}
[31m
Step 4, get lesson list by course id[0m
[32mcore.get_lesson_list(course_id)[0m
Traceback (most recent call last):

**Comment by Fatpandac** [comment]
你需要设置账号密码到终端环境变量`USERS` 和 `PASSWORD`
```shell
export USERS=你的账号
export PASSWORD=你的密码
```

**Comment by abai2020** [comment]
> 你需要设置账号密码到终端环境变量`USERS` 和 `PASSWORD`
> 
> ```shell
> export USERS=你的账号
> export PASSWORD=你的密码
> ```

是在[sample.py](https://github.com/Fatpandac/hackcqooc/blob/main/sample.py)，这里面修改吗，感谢大佬解答，麻烦了

**Comment by Fatpandac** [comment]
如果你不想设置变量，那就直接将这[两行代码](https://github.com/Fatpandac/hackcqooc/blob/main/sample.py#L7-L8)变量赋值为你的账号密码
```py
username = os.environ.get("USERS")
password = os.environ.get("PASSWORD")
```

**Comment by abai2020** [comment]
> 

我把USERS和PASSWORD改成我自己的账号和密码然后还是登录失败

**Comment by Fatpandac** [comment]
麻烦提供错误信息

**Comment by abai2020** [comment]
> 麻烦提供错误信息

![image](https://user-images.githubusercontent.com/68065125/188813214-5dd2292b-59ac-42e5-ab6d-4f8b85d34785.png)

**Comment by Fatpandac** [comment]
你代码改错了🫠
```py
username = os.environ.get("USERS")
password = os.environ.get("PASSWORD")
```
是把 `os.environ.get("USERS")` 替换为你的账号，`os.environ.get("PASSWORD")` 替换为你的密码

**Comment by abai2020** [comment]
收到

**Comment by abai2020** [comment]
![image](https://user-images.githubusercontent.com/68065125/188816145-5ff26db3-392f-4a0e-ac6f-9dd36b3e1af5.png)
这种正常吗，获取课程成功，然后就结束了

**Comment by Fatpandac** [comment]
有看到登录成功就可以了
<img width="360" alt="image" src="https://user-images.githubusercontent.com/30423976/188816659-88e68a1b-c40b-4312-89fb-e3adb72c693c.png">

**Comment by abai2020** [comment]
登录成功了，但是怎么获取测验列表，麻烦大佬了

**Comment by Fatpandac** [comment]
```py
def get_exam_papers_info(course_id: str, start: int = 0, limit: int = 200) -> dict
```
用上面这个方法
```py
core.get_exam_papers_info(course_id)
```

**Comment by abai2020** [comment]
好的
